### ISSUE TITLE
Supporting prettier

### ISSUE THREAD

**Issue by stefvw93** [owowagency/eslint-config#11]
I did a first attempt to add prettier support to this config; there are some decisions to be made so let's discuss.

**About prettier**

First of all. If we want to support Prettier, we should be aware that prettier is _very_ opinionated. This has pro's and cons. I personally prefer Prettier because of the simple fact that it makes me more productive and efficient -- since I spend _no time_ on manually formatting my code. Though, some people dislike the opinionated nature of Prettier.

Committing to Prettier will most prominently mean that we will use ESLint for _code quality_, and Prettier for _formatting_.

**Before we start working on this**

We need to decide on some things:
- Should we commit to Prettier?
- Should we incorporate Prettier into @owowagency/eslint-config?
- Should we create a separate Prettier config package e.g. @owowagency/prettier-config?
- Should we simply add instructions to the readme on how to add Prettier?

**Incorporating Prettier and ESLint**

When using Prettier: Prettier is for _formatting_, ESLint is for _code quality_.

If we want to support prettier in this package, there are some formatting rules that need to be omitted/removed from ESLint configs:

- array-bracket-spacing
- arrow-parens
- block-spacing
- brace-style
- comma-dangle
- comma-spacing
- comma-style
- indent
- key-spacing
- no-multi-spaces
- object-curly-spacing
- operator-linebreak
- quote-props
- semi
- space-before-function-paren
- template-curly-spacing
- unicorn/number-literal-case
- quotes

All of these are formatting rules -- therefor handled by Prettier, thus it is better to remove these rules from ESLint config.

Feature branch https://github.com/owowagency/eslint-config/tree/feature/prettier.

**Comment by thomasowow** [comment]
> since I spend no time on manually formatting my code

Indeed a nice feature. However the same could be achieved in most IDE's.

Personally I like the fact that we now have a set of rules that we all like. And if we all agree we do not like a single rule anymore, we can just update the package.

**Comment by stefvw93** [comment]
> I would vote against trying to get IDE's to do all the formatting, it's a mess when working together.

@thomasowow I agree with @basbakx that leaving the formatting to the IDE is problematic, since it is harder to have everybody working in the same IDE, with the same plug-ins, settings. There will inevitably be varying set-ups that break down code uniformity.

When creating a separate package, we can separate concerns a bit, but ultimately we would always be using one or the other (with prettier, without prettier). So maybe we should decide on just adding prettier to the config?

**Comment by stefvw93** [comment]
I went ahead and made a [PR](https://github.com/owowagency/eslint-config/pull/13) that integrates Prettier as an ESLint rule.
